<?php

$api_keys = [
    'AI_API_KEY' => 'AIzaSyD6JsiCJO3x15E9RAWLNk0N9p_dK2AYyFM',
    'GROQ_API_KEY' => 'YOUR_GROQ_API_KEY_HERE',
    'CLAUDE_API_KEY' => 'YOUR_CLAUDE_API_KEY_HERE',
    'GEMINI_API_KEY' => 'AIzaSyD6JsiCJO3x15E9RAWLNk0N9p_dK2AYyFM',
    'HF_API_KEY' => 'YOUR_HF_API_KEY_HERE',
];